### ISSUE TITLE
[Feature Request] Support parsing `blob` and `tree` urls

### ISSUE THREAD

**Issue by devxpy** [nephila/giturlparse#10]
Can you please add support for "blob" urls like
"https://github.com/jessfraz/dockerfiles/blob/master/buttslock/buttslock.py"

and "tree" urls like
"https://github.com/jessfraz/dockerfiles/tree/master/buttslock"

**Comment by yakky** [comment]
@devxpy thanks for reporting. PR #19 should provide the required feature
