### ISSUE TITLE
Supporting hg urls from bitbucket 

### ISSUE THREAD

**Issue by virresh** [nephila/giturlparse#11]
The library is currently able to successfully parse bitbucket urls for git.
Also https urls of hg for bitbucket are being parsed successfully as well, 
If support is added for the ssh urls of hg as well, that would be great 

e.g
HTTPS url for hg at BitBucket : https://virresh@bitbucket.org/virresh/mercurialtest  
SSH url for hg at BitBucket : ssh://hg@bitbucket.org/virresh/mercurialtest  

HTTPS url for git at BitBucket : https://virresh@bitbucket.org/virresh/gittest.git
SSH url for git at BitBucket :  git@bitbucket.org:virresh/gittest.git

**Comment by yakky** [comment]
@virresh thanks for reporting this

Unfortunately I don't know when I will be able to tackle this
If you would like to contribute with a patch., it would be more than welcome and I am willing to provide help and mentoring to help whoever would want to work on this

**Comment by yakky** [comment]
As bitbucket does not support mercurial anymore, we can close this
