### ISSUE TITLE
URL and repo regex should be non-greedy (maybe)

### ISSUE THREAD

**Issue by GreatBahram** [nephila/giturlparse#18]
Hello, 
I think there is a problem in this `regex` or maybe all of them:
```python
import re

pattern = r'https://(?P<domain>.+)/(?P<owner>.+)/(?P<repo>.+?)(?:\.git)?$'
url = 'https://github.com/nephila/giturlparse/blob/master/giturlparse/platforms/github.py'

match = re.match(pattern, url).groupdict()
```
I suppose, this is an invalid URL, for simple reason `git clone` would not accept it; however, when we check the match object, things are a bit strange,:
```
{'domain': 'github.com/nephila/giturlparse/blob/master/giturlparse',
 'owner': 'platforms',
 'repo': 'github.py'}
```
If we make them non-greedy, it would a little better:
```python
pattern = r'https://(?P<domain>.+?)/(?P<owner>.+?)/(?P<repo>.+?)(?:\.git)?$'
match = re.match(pattern, url).groupdict()
```
```
{'domain': 'github.com',
 'owner': 'nephila',
 'repo': 'giturlparse/blob/master/giturlparse/platforms/github.py'}
```
* I don't know whether I'm right or not, but I think it's not normal to see a `/` in repo field, is it?
If it is not, so you guys should return `False` for `valid` attribute, am I right?
* Is there any harm to make all the patterns non-greedy? Is there any circumstances that there would be '/' in the repo field?

@yakky

**Comment by GreatBahram** [comment]
I think the issue #10 is somehow related to this problem.

**Comment by yakky** [comment]
@GreatBahram thanks for reporting. In PR #19 I implemented a slightly different logic, which should be more consistent across url schemas
