### ISSUE TITLE
ssh:// github urls not supported

### ISSUE THREAD

**Issue by sbidoul** [nephila/giturlparse#20]
Hi,

I noticed ssh:// urls are not recognized, such as `ssh://git@github.com/Org/Repo.git`.

I tried a PR but the current code structure does not make it very easy to support this properly and I ran out of time. Perhaps this could be taken into account in #10?

Thanks for this lib!

**Comment by yakky** [comment]
@sbidoul thanks for reporting this, it will be fixed in #19
