### ISSUE TITLE
github urls with access token are not supported

### ISSUE THREAD

**Issue by godfryd** [nephila/giturlparse#21]
Such urls has this form: https://\<access-token\>@github.com/....
For example:
https://fiuahjrehfakhdhauwe@github.com/nephila/giturlparse

**Comment by yakky** [comment]
@godfryd thanks for reporting
I need to go back to work on #19 where we should be able to easily add this

**Comment by protoroto** [comment]
@godfryd Could you try on latest version? I'm able to parse that url correctly now

**Comment by godfryd** [comment]
Hello,

I tried giturparse 0.11.1 on the URL:  https://fiuahjrehfakhdhauwe@github.com/nephila/giturlparse

I run:
```python
p=giturlparse.parse('https://fiuahjrehfakhdhauwe@github.com/nephila/giturlparse')
print(p.data)
```
Parsed data does not seem well:
```python
{'port': '',
 'path_raw': '',
 'groups_path': '',
 'owner': 'nephila',
 '_user': 'git',
 'protocols': ['https'],
 'protocol': 'https',
 'domain': 'fiuahjrehfakhdhauwe@github.com',
 'pathname': '/nephila/giturlparse',
 'repo': 'giturlparse',
 'path': '',
 'branch': '',
 'url': 'https://fiuahjrehfakhdhauwe@github.com/nephila/giturlparse',
 'platform': 'gitlab'}
 ```

I would expect that `platform` is `github` not `gitlab`,
`domain` seems to be incorrect,
`access token` could be stored in `user` field.

**Comment by protoroto** [comment]
@godfryd You're right: I guess access tokens are not supported yet. I'll look into it

**Comment by protoroto** [comment]
@godfryd I'm digging into this: it looks like urls with access token like the one you mentioned `https://<access_token>@github.com/nephila/giturlparse` are not supported by github/gitlab . I'm seeing that urls like https://oauth2:<access_token>@github.com/nephila/giturlparse are instead valid and supported (both for gitlab and github), so I'll work on this feature.

**Comment by godfryd** [comment]
ok, thanks :)

Michał Nowikowski

**Comment by protoroto** [comment]
@godfryd Hey! We've just release 0.12.0 that should support those urls.
