### ISSUE TITLE
in BasePlatform FORMATS should be PATTERNS and PATTERNS should be FORMATS

### ISSUE THREAD

**Issue by godfryd** [nephila/giturlparse#40]
## Description

I tried to parse "http://localhost:3000/gitea/demo.git" and it fails because the base parser has switched settings
i.e. BasePlatform's FORMATS and PATTERNS are switched.

## Steps to reproduce

```python
import giturlparse
giturlparse.parse("http://localhost:3000/gitea/demo.git")
```
and this raises an exception.

## Versions

0.10.0

## Expected behaviour

It should be parsed correctly.

## Actual behaviour

Exception is raised.

**Comment by yakky** [comment]
Thanks @godfryd for reporting this, fixed in #50
