### ISSUE TITLE
Fails to parse repo name  when GitLab repo name contains a `-` character

### ISSUE THREAD

**Issue by nasifimtiazohi** [nephila/giturlparse#42]
## Description

Fails to parse repo name  when GitLab repo name contains a `-` character.

## Steps to reproduce

test case: `s = 'https://gitlab.com/sheepkill15/cypress-helper/-/blob/main/.vscodeignore'`
## Versions

Python >= 3.7
gitulrparse = 0.10.0

## Expected behaviour

`parse(s).repo == 'cypress-helper'`

## Actual behaviour

`parse(s).repo == '-'`

**Comment by protoroto** [comment]
@nasifimtiazohi We've released 0.12.0 that should fix this, thanks to @boozec ! :)
