### ISSUE TITLE
cannot parse github url

### ISSUE THREAD

**Issue by nasifimtiazohi** [nephila/giturlparse#43]
fails to parse 'https://github.com/rubygems/rubygems/'. The issue arises from having a `/` character at the end.

```
>>> from giturlparse import parse
>>> s = 'https://github.com/rubygems/rubygems/'
>>> p = parse(s)
>>> p.host
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nasifimtiaz/Library/Caches/pypoetry/virtualenvs/package-locator-2SDQOXag-py3.9/lib/python3.9/site-packages/giturlparse/result.py", line 43, in host
    return self.domain
AttributeError: 'GitUrlParsed' object has no attribute 'domain'
>>> p.owner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GitUrlParsed' object has no attribute 'owner'
```

**Comment by alingse** [comment]
+1 see this should strip the last `/` 
@yakky 

if you like, I can make an pull request for this.

**Comment by davidjray** [comment]
Seeing a similar error `AttributeError: 'GitUrlParsed' object has no attribute '_platform_obj'`

Removing the trailing slash resolved the issue for me.

**Comment by yakky** [comment]
Thanks @davidjray @alingse @nasifimtiazohi for reporting this. It has been fixed by an unrelated PR, but I added this case in #53 to guard against regressions
