### ISSUE TITLE
Upload githurlparse to pypi

### ISSUE THREAD

**Issue by gene1wood** [nephila/giturlparse#5]
Would you upload giturlparse (your fork of giturlparse.py) to pypi so that it can be used easily by folks?

Would you also update [this line in the README](https://github.com/yakky/giturlparse/blame/9654986c7eb9fb2b725f34a5d6ba60a61ac14b74/README.rst#L17) as currently if you follow what it says it installs `FriendCode`'s original, not your fork. Once you've uploaded to pypi it should say

```
    pip install giturlparse
```

**Comment by yakky** [comment]
Thanks @gene1wood for popping in
If it might be of interest for others, yes.
I released 0.9.1 as a snapshot of the current master
For a proper release I will need to bring this in lined with our release standard (and I will likely move this to the nephila organization)
I'll keep this open until I completed the process

**Comment by pycampers** [comment]
I am using it to create [this](https://github.com/pycampers/docapt).

Thanks for actively maintaining  :)

**Comment by yakky** [comment]
@pycampers nice!

**Comment by virresh** [comment]
We are also looking for [url parser](https://github.com/coala/coala-bears/issues/2330)
Would be great if you could release it soon !
Thanks :)

**Comment by yakky** [comment]
@virresh sorry, I forgot to close this
release 0.9.1 has been released in January https://pypi.python.org/pypi/giturlparse
I still did not have time to update meta files etc, but the code is already one pip install away :)
