### ISSUE TITLE
Latest version causes lots of data to go to stdout

### ISSUE THREAD

**Issue by Sillocan** [nephila/giturlparse#66]
## Description

Stdout is polluted with "didn't match" print statements. This causes a lot of extra logging for cloud based services and causes tests expecting no stdout to fail.

## Steps to reproduce

Simply run tox and view the unit test output

## Versions

Any version

## Expected behaviour

Nothing is logged to stdout unless it is an actual error, which ideally goes to stderr. If you want to keep debug logs around then using `logging.debug`

**Comment by Sillocan** [comment]
Opened an MR to resolve this https://github.com/nephila/giturlparse/pull/65

**Comment by protoroto** [comment]
@Sillocan I've just released 0.11.1 version, thanks for contributing!
