### ISSUE TITLE
License metadata mischmatch

### ISSUE THREAD

**Issue by hroncok** [nephila/giturlparse#7]
https://github.com/nephila/giturlparse/blob/a29728dbe3e163df3524f8f6e5627ac458a250ec/setup.py#L36

Contradicts README and LICENSE.

**Comment by jayvdb** [comment]
Comes from https://github.com/nephila/giturlparse/commit/d6ade40c224e6da4e4d069e88625aae95bba54f6#diff-2eeaed663bd0d25b7e608891384b7298R35 ; likely a copy&paste accident.

**Comment by yakky** [comment]
@hroncok thanks for reporting
